name: a
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  http: ^0.13.5
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  easy_localization: ^3.0.1
  easy_localization_loader:
    git: https://github.com/aissat/easy_localization_loader.git
  flutter_screenutil: ^5.5.4
  flutter_statusbarcolor_ns: ^0.4.0
  restart_app: ^1.1.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/
    - assets/fonts/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Erode
      fonts:
        - asset: assets/fonts/Erode-Bold.otf
          weight: 700
        - asset: assets/fonts/Erode-Medium.otf
          weight: 500
        - asset: assets/fonts/Erode-Semibold.otf
          weight: 600
        - asset: assets/fonts/Erode-Regular.otf
          weight: 500
        - asset: assets/fonts/Erode-Italic.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages